# Generated by Django 6.0.2 on 2026-03-30 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_userprofile_monthly_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="saved_on",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
