# Generated by Django 6.0 on 2026-03-30 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_goal_saved_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='started_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
